version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/docker/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
notifications:
  endpoints:
    - name: express_listener
      disabled: false
      url: localhost:8080
      headers:
        Content-Type: "application/json"
      timeout: 500
      threshold: 5
      backoff: 1000
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
