version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/docker/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
notifications:
  endpoints:
    - name: express_listener
      disabled: false
      url: http://registry:8080
      headers:
        Accept:
          - text/plain
      timeout: 100000000
      threshold: 5
      backoff: 1000
      ignoredmediatypes:
        - application/octet-stream
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
