version: '2.0'
services:
  storage:
    image: hypriot/armhf-busybox
    volumes:
      - /var/lib
      - ./config.yml:/etc/docker/registry/config.yml
  cache:
    image: hypriot/rpi-redis
  backend:
    image: pandawan1991/rpi-docker-registry
    ports:
    - 5000:5000
    links:
      - cache
      - storage
    volumes_from:
      - storage
    environment:
      SETTINGS_FLAVOR: local
      STORAGE_PATH: /var/lib
      SEARCH_BACKEND: sqlalchemy
      CACHE_REDIS_HOST: cache
      CACHE_REDIS_PORT: 6379
      CACHE_LRU_REDIS_HOST: cache
      CACHE_LRU_REDIS_PORT: 6379
