version: '2.0'
services:
  backend:
    image: pandawan1991/rpi-docker-registry
    restart: always
    ports:
      - 5000:5000
    networks:
      - outside
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - registry-volume:/var/lib/docker/registry
    environment:
      SETTINGS_FLAVOR: local
      STORAGE_PATH: /var/lib/docker/registry
      SEARCH_BACKEND: sqlalchemy
volumes:
  registry-volume:
    external: true
networks:
  outside:
    external: true
